### ISSUE TITLE
BasicConvLSTM batch size can't be different between training and inference

### ISSUE THREAD

**Issue by TonyGongjc** [TolicWang/RNN#1]
Hi Wang, 

Thanks for your sharing of peephole version ConvLSTM. However I found that the first dimension of peephole parameters 'w_ci', 'w_cf' and 'w_co' is related to batch size, which mades me unable to set different batch size during training and inference. Is it a bug or it has to be so?

Thank you so much.

**Comment by TolicWang** [comment]
Actually,  any model in Tensorflow, as far as I know, different batch size can not be setted whatever in training or in inference process. Hence, I suggest that you can set the batch size in tf.placeholder with `None`, which will avoid this problem you suffered.

**Comment by TonyGongjc** [comment]
Thanks for your quick reply. More specifically, starting from Line 90 in ConvLSTM.py (peephole part),  'w_ci' is defined by vs.get_variable("w_ci", cell.shape, inputs.dtype), which results in shape [512, 7, 7, 128] during training, and 512 is the batch size I set in this case. However if I set batch size to 1000 during inference, the shape of 'w_ci' will change to  [1000, 7, 7, 128],  which, will fail because this is not consistent with the training shape. 

Apparently the first dimension of 'w_ci' cannot be None or -1 in this case otherwise the variable cannot be created. However once the variable is created, the shape is also fixed, which leads to unchangeable batch size.

If I set off the peephole mode, this problem will not appear which means I can set different batch size. So this problem is a little bit weird to me. I will try fixing it.

**Comment by TolicWang** [comment]
Thanks for your reminder. After check carefully,  it should be a vital bug. And it has been debuged as follow:
```
            kernel_shape = cell.shape.as_list()[-3:]
            w_ci = vs.get_variable(
                "w_ci", kernel_shape, inputs.dtype)
            w_cf = vs.get_variable(
                "w_cf", kernel_shape, inputs.dtype)
            w_co = vs.get_variable(
                "w_co", kernel_shape, inputs.dtype)
```

You can change your code in your project, and if there is any problem, please feel free to contact me.

**Comment by TonyGongjc** [comment]
Everything looks well! Thanks for your help!
